language: node_js
node_js: 
    - '8.4.0'

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - node_modules

before_install:
  - git config --global user.name "Wizard67"
  - git config --global user.email wizard67.hjn@gmail.com
  - git config --global core.autocrlf  false
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$TOKEN@github.com/Wizard67/element-ui-demo.git master:gh-pages

notifications:
  email: 
    on_success: never